### ISSUE TITLE
Device Group Support

### ISSUE THREAD

**Issue by NotReallyADeveloper** [logon84/pySVS#2]
As a user with multiple subs, I would like a solution that would allow me to change the settings on more than one sub at the same time.

**Comment by logon84** [comment]
Hi. At the same time would be impossible: your bluetooth connection can only handle 1 connection at a time, not only for svs devices but also for the rest. At most, all that could be done is launch a script, scan for devices, filter them by mac (I suppose every svs mac starts by 08:eb:ed) and then select one of them and pass this mac to the pySVS program and use it as value for SVS_MAC_ADDRESS variable.

**Comment by NotReallyADeveloper** [comment]
Yeah - at the same time wasn’t the right expression as I know about that limitation. More like macro support to an arbitrary number of configured subs. 

What sort of delay would be anticipated when switching between device connections? Would it be possible to support multiple BT transmitters simultaneously on the same host (and have each bound to their own sub)? Most users would have two at most although more might be the case for a smaller user base.
